# from Database import Database
import pandas as pd
# db = Database("/Users/Goon/Desktop/Duke/ECE496/PFHV/db/db.ini")

# print(db.macro_regional_df.head())
#print(db.homes_df.head())
#print(db.history_df.head())
#print(db.macro_national_df.head())

# ny_homes = pd.read_csv("./../data/homes_ny.csv")
# austin_homes = pd.read_csv("./../data/homes_austin.csv")
# print('original')
# print('new york')
# print(ny_homes.head())
# print(len(ny_homes.index))
# print('austin')
# print(austin_homes.head())
# print(len(austin_homes.index))
# ny_homes['id'] = ny_homes['id'].apply(lambda x: x+1)
# austin_homes['id'] = austin_homes['id'].apply(lambda x: x+2401)
# print('after')
# print(ny_homes.head())
# print(austin_homes.head())
# complete_df =ny_homes.append(austin_homes, ignore_index=True)
# print(len(complete_df.index))
# complete_df.to_csv("homes_complete.csv", index=False)
# ny_history = pd.read_csv("./../data/history_ny.csv")
# austin_history = pd.read_csv("./../data/history_austin.csv")
# print('original')
# print('new york')
# print(ny_history.head())
# print(len(ny_history.index))
# print('austin')
# print(austin_history.head())
# print(len(austin_history.index))
# ny_history['home_id'] = ny_history['home_id'].apply(lambda x: x+1)
# austin_history['home_id'] = austin_history['home_id'].apply(lambda x: x+2401)
# print('after')
# print(ny_history.head())
# print(austin_history.head())
# complete_df =ny_history.append(austin_history, ignore_index=True)
# print(len(complete_df.index))
# complete_df.to_csv("history_complete.csv", index=False)